import type { NextPage } from 'next';
import Head from 'next/head';

import { Button } from '../components/Shared/Button';
import { GlobeIcon } from '../components/Shared/Svg/Icons';
import { Logo } from '../components/Shared/Logo';

import { NavbarExpandedMenu } from '../components/NavbarExpandedMenu';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex items-center p-7">
        <div className="flex items-center">
          <Button variant="TEXT">
            <Logo />
          </Button>
          <NavbarExpandedMenu />
        </div>

        <div className="flex ml-auto">
          <div className="mr-4">
            <Button className="mr-1" variant="OUTLINE">
              Log In
            </Button>
            <Button className="mr-1">Sign up</Button>
          </div>
          <Button className="mr-1" variant="SECONDARY">
            <GlobeIcon />
          </Button>
          <Button className="mr-1" variant="SECONDARY">
            USD
          </Button>
        </div>
      </nav>
    </div>
  );
};

export default Home;
