import type { NextPage } from 'next';
import Head from 'next/head';

import { Button, ExpandableButton } from '../components/Shared/Button';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button className="mr-1">Sign up</Button>
        <Button className="mr-1" variant="OUTLINE">
          Log In
        </Button>
        <Button className="mr-1" variant="SECONDARY">
          USD
        </Button>
        <ExpandableButton>Derivatives</ExpandableButton>
      </div>
    </div>
  );
};

export default Home;
